name: Automated Email Newsletter Bot

on:
  repository_dispatch:
    types: [new_signup]

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository Code
      uses: actions/checkout@v4

    - name: Set up Python Environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Execute Bot Script
      env:
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        GITHUB_CLIENT_PAYLOAD: ${{ toJson(github.event.client_payload) }}
      run: python send_email.py  # <-- Changed this line
